# Generated by Django 5.2.4 on 2025-09-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(blank=True, max_length=150)),
                ('nombre_cientifico', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('fauna', 'Fauna'), ('flora', 'Flora')], max_length=20)),
                ('zona', models.CharField(blank=True, max_length=150)),
                ('estado_conservacion', models.CharField(choices=[('EX', 'Extinta'), ('EW', 'Extinta en Estado Silvestre'), ('CR', 'En Peligro Crítico'), ('EN', 'En Peligro'), ('VU', 'Vulnerable'), ('NT', 'Casi Amenazada'), ('LC', 'Preocupación Menor'), ('DD', 'Datos Insuficientes'), ('NA', 'No evaluada')], default='NA', max_length=2)),
                ('imagen_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250)),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('imagen_url', models.URLField(blank=True)),
            ],
        ),
    ]
