# Generated by Django 5.2.7 on 2025-10-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagen_post_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
